version: '3.5'

services:

  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ce:${TAG}
    hostname: ${HOSTNAME}
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab
