version: '3.5'

services:

  gitlab:
    container_name: ${GITLAB_CONTAINER}
    image: gitlab/gitlab-ce:${TAG}
    hostname: ${NGINX_HOSTNAME}
    environment:
      - VIRTUAL_HOST=${GITLAB_HOSTNAME}
      - LETSENCRYPT_HOST=${GITLAB_HOSTNAME}
      - LETSENCRYPT_EMAIL=${GITLAB_CONTAINER}@no-reply.com
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab
    restart: always

networks:
  default:
    external:
      name: ${NGINX_PROXY_NET}
